/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>
#include <vector>

using namespace std;

int main(){

  int n,sum = 0;
  cin>>n;
  vector<int> a(n);
  a[0] = 1;
  a[1] = 2;
  for(int i = 2; i < n; i++){
    a[i] = a[i - 2] + a[i - 1];
  }
  for(int i = 0; i < n; i++){
    if(a[i] % 2 == 0){
        sum += a[i];
    }
  }

  cout<<"The sum is: "<<sum<<endl;


  return 0;

}
